In [1]:
import pandas as pd
import os

df = pd.read_csv("../data/processed/online_retail_clean.csv")
df.head()

,invoice_no,stockcode,description,quantity,invoice_date,unit_price,customer_id,country,source_sheet,is_cancellation,sales_amount
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,Year 2009-2010,False,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Year 2009-2010,False,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Year 2009-2010,False,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,Year 2009-2010,False,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Year 2009-2010,False,30.0

In [2]:
df.shape

(805549, 11)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805549 entries, 0 to 805548
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   invoice_no       805549 non-null  int64
 1   stockcode        805549 non-null  object
 2   description      805549 non-null  object
 3   quantity         805549 non-null  int64
 4   invoice_date     805549 non-null  object
 5   unit_price       805549 non-null  float64
 6   customer_id      805549 non-null  float64
 7   country          805549 non-null  object
 8   source_sheet     805549 non-null  object
 9   is_cancellation  805549 non-null  bool
 10  sales_amount     805549 non-null  float64
dtypes: bool(1), float64(3), int64(2), object(5)
memory usage: 62.2+ MB

In [4]:
df.isna().sum().sort_values(ascending=False)

invoice_no         0
stockcode          0
description        0
quantity           0
invoice_date       0
unit_price         0
customer_id        0
country            0
source_sheet       0
is_cancellation    0
sales_amount       0
dtype: int64

In [5]:
df[["quantity","unit_price","sales_amount"]].describe()

            quantity     unit_price   sales_amount
count  805549.000000  805549.000000  805549.000000
mean       13.290522       3.206561      22.026505
std       143.634088      29.199173     224.041928
min         1.000000       0.001000       0.001000
25%         2.000000       1.250000       4.950000
50%         5.000000       1.950000      11.850000
75%        12.000000       3.750000      19.500000
max     80995.000000   10953.500000  168469.600000

In [6]:
df["invoice_date"] = pd.to_datetime(df["invoice_date"])
df["invoice_date"].min(), df["invoice_date"].max()

(Timestamp('2009-12-01 07:45:00'), Timestamp('2011-12-09 12:50:00'))

In [7]:
df["customer_id"].nunique(), df["invoice_no"].nunique(), df["stockcode"].nunique()

(5878, 36969, 4631)